PostHog/posthog-js-lite

- package.json
- src/index.ts
- src/types.ts
- src/utils/context.ts
- tsconfig.json
Previously the call to `posthog.identify(distinctId, properties)` required a string `distinctId` argument, even though `null` is perfectly acceptable if you just want to set properties.
Typescript was not in `strict` mode, thus the `| null` part in `string | null` was omitted from the generated definitions.
> Add stricter type checking to the library

- examples/example-node/example.ts
- examples/example-node/server.ts
- posthog-node/index.ts
- posthog-node/src/posthog-node.ts
- posthog-node/test/feature-flags.spec.ts
- posthog-node/test/posthog-node.spec.ts
> Rename export for node to PostHog

- examples/example-node/example.ts
- posthog-core/src/index.ts
- posthog-core/src/types.ts
- posthog-core/test/posthog.featureflags.spec.ts
- posthog-core/test/posthog.init.spec.ts
- posthog-core/test/test-utils/PostHogCoreTestClient.ts
- posthog-react-native/CHANGELOG.md
- posthog-react-native/jest.config.js
- posthog-react-native/package.json
- posthog-react-native/src/posthog-rn.ts
- posthog-react-native/src/storage.ts
- posthog-react-native/test/init.spec.ts
- posthog-react-native/test/storage.spec.ts
- posthog-web/src/posthog-web.ts
- yarn.lock
Just like https://github.com/PostHog/posthog-js/pull/444 but for react-native.
@benjackwhite I could use some help figuring out this works for react-native.
Current issues I'm facing:
1. The CI doesn't seem to be testing `posthog-react-native` ?
2. How do I get the new test created specifically for react-native to run? Unfamiliar with expo, and it's complaining about those imports.
3. Can you help testing a 'live' version of this and confirming it works?
> feat(feature-flags): Add bootstrap option for feature flags

- posthog-react-native/src/storage.ts
This PR's changes are only relevant to the RN SDK.
Before: all values set while stored data was being loaded would get overwritten once the data was done loading
After: values that have been set before loading was completed are preserved
I ran into this case while changing opt-in status immediately after constructing a PostHog instance
> fix: Loaded storage does not overwrite changes made while loading

- posthog-node/package.json
- posthog-react-native/package.json
- posthog-web/package.json
I released a new version of posthog-react-native, but `npm publishg` did not build the new library, and thus I published the old one again under a new number.
This changes the scripts in package.json to always run yarn build before publishing
> add prepublishOnly

- posthog-node/src/feature-flags.ts
- posthog-node/test/feature-flags.spec.ts
Add support for date operators in feature flags local evaluation, modeled after https://github.com/PostHog/posthog-python/pull/75
> Local eval date operators support

- posthog-react-native/src/hooks/useFeatureFlag.ts
- posthog-react-native/src/hooks/useFeatureFlags.ts
`useFeatureFlag` and `useFeatureFlags` were violating the [rules of hooks](https://reactjs.org/docs/hooks-rules.html#explanation) by calling hooks conditionally. This PR fixes that.
See also https://github.com/PostHog/posthog-js-lite/issues/34#issuecomment-1321891181
> fix(flags): hooks

- examples/example-node/example.ts
- posthog-core/src/index.ts
- posthog-core/src/types.ts
- posthog-core/test/posthog.featureflags.spec.ts
- posthog-node/CHANGELOG.md
- posthog-node/package.json
- posthog-node/src/posthog-node.ts
This will auto timeout any calls after 10 seconds (which may be too aggressive?). People were running into issues when we had slow API calls as it'd wait forever.
> feat: Add timeout option for all calls

- posthog-react-native/src/PostHogProvider.tsx
The `autocapture` prop is typed as `boolean | PostHogAutocaptureOptions`, but passing `false` does nothing at all.
This PR makes the provider behave more intuitively when autocapture is false.
If ignoring the `false` option was intended, the `autocapture` prop should have been typed as `true | PostHogAutocaptureOptions`.
> Respect autocapture=false

- posthog-core/src/index.ts
- posthog-core/src/types.ts
- posthog-core/test/posthog.featureflags.spec.ts
- posthog-node/src/feature-flags.ts
- posthog-node/test/feature-flags.spec.ts
- posthog-node/test/posthog-node.spec.ts
~~Shouldn't go in until accompanying posthog PR is done.~~ It's done!
When decide partially computes flag, this PR ensures that we upsert flag information, rather than replace. Replace only happens when there were no errors on decide.
> feat(feature-flags): Allow upserting decide v3 responses

- posthog-core/src/index.ts
- posthog-core/src/types.ts
- posthog-core/test/posthog.featureflags.spec.ts
- posthog-node/src/feature-flags.ts
- posthog-node/src/posthog-node.ts
- posthog-node/test/feature-flags.spec.ts
- Add ability to bootstrap payloads
- init can now accept `featureFlagPayloads: Record<string, JsonType>`
> feat(feature-flag): ff bootstrap payload option

- posthog-core/src/index.ts
- posthog-core/test/posthog.featureflags.spec.ts
- posthog-node/src/posthog-node.ts
- the returned payload may be a stringified json payload
- try-catch parse json
> chore: feature flag payload try to parse json

- posthog-core/src/index.ts
- posthog-core/test/posthog.groups.spec.ts
- posthog-node/src/posthog-node.ts
- posthog-node/test/posthog-node.spec.ts
- posthog-react-native/CHANGELOG.md
- posthog-react-native/package.json
- posthog-web/CHANGELOG.md
- posthog-web/package.json
For client SDKs we should use the distinctId for the current user and for server SDKS as hash of the key and id. We were always acting like a server SDK
* Fixes this and adds tests
- Ensures the distinctId used in `.groupIdentify` is the same as the currently identified user
> fix: Different groupIdentify behaviour for node lib

- posthog-node/package.json
- posthog-node/src/types.ts
- https://github.com/PostHog/posthog-js-lite/issues/65
- makes the import relative
> fix: Make type import relative so typescript builds correctly

- posthog-node/package.json
AbortController and AbortSignal are only supported in 15 and above: https://github.com/PostHog/posthog-js-lite/issues/51
> Restrict to node 15.0.0 and above

- posthog-core/src/index.ts
- posthog-react-native/CHANGELOG.md
- posthog-react-native/package.json
- posthog-web/CHANGELOG.md
- posthog-web/package.json
We background refresh the feature flags but don't handle if there is a bad response (e.g. due to network issues)
Closes https://github.com/PostHog/posthog-js-lite/issues/70
* Adds a new non-async method which takes an optional callback
* Changes background refreshes to use this
- Fixes an issue where background network errors would trigger unhandled promise warnings
> fix: Catch promise error for background refreshes

- posthog-core/src/index.ts
- posthog-core/test/posthog.featureflags.spec.ts
- posthog-core/test/posthog.identify.spec.ts
This is part 1 of 2 of making posthog core stateless.
The gameplan:
Part 1: Split out two abstract base classes: PostHogCore (existing class), and PostHogCoreStateless (new class, which is also the base class of PosthogCore).
The reasoning behind this is to keep changes minimal, and to ensure that current tests pass without any changes. The PostHogCore interface remains the same, so technically nothing should change because of part 1.
Part 2: In a future PR, I will refactor posthog-node to depend on `PostHogCoreStateless` instead of `PostHogCore`.
> feat: Make PostHog Core stateless

- .github/workflows/release.yml
Restricting Node to 15+ seems to have broken CI 😅 
> Update node version for release.yml

- .github/workflows/release.yml
See run fail:  https://github.com/PostHog/posthog-js-lite/actions/runs/4183402196/jobs/7247712879
> Jest-matcher requires node 16 for release

- posthog-node/CHANGELOG.md
- posthog-node/package.json
- posthog-node/src/posthog-node.ts
- posthog-node/test/posthog-node.spec.ts
Stateless refactor introduced a bug with identify on node
* Fix this to use $set and also handle if someone treats it like a `capture` call.
> fix: Identify $set for Node

- posthog-core/src/index.ts
- posthog-node/CHANGELOG.md
- posthog-node/package.json
- posthog-node/src/feature-flags.ts
- posthog-node/src/posthog-node.ts
Fixes https://github.com/PostHog/posthog-node/issues/83
A proper fix for https://github.com/PostHog/posthog-js-lite/pull/44
Tested locally, in debug mode, debug logs show up. In non-debug mode, they don't show up.
> fix: add debug logs only in debug mode

- posthog-node/CHANGELOG.md
- posthog-node/package.json
- posthog-node/src/feature-flags.ts
- posthog-node/src/types.ts
- posthog-node/test/feature-flags.spec.ts
Part of https://github.com/PostHog/meta/pull/90
Enables locally evaluating all cohorts.
> feat(flags): Enable local evaluation for all cohorts

- jest.config.js
- posthog-core/src/index.ts
- posthog-core/src/utils.ts
- posthog-core/test/posthog.flush.spec.ts
- posthog-node/src/feature-flags.ts
- posthog-node/src/fetch.ts
- posthog-node/test/feature-flags.spec.ts
- posthog-node/test/posthog-node.spec.ts
- posthog-web/tsconfig.json
- tsconfig.json
- Axios throws on HTTP errors (non-2xx), fetch does not
- There's no way to listen for PostHog errors
- `shutdownAsync` throws when the associated flush throws, but the flush interval ignores errors
- `retriable` delays even if everything succeeded
- I added `validateStatus: () => true` to Axios. This makes sure Axios doesn't throw any HTTP errors.
- I added two errors: PostHogFetchHttpError (non-2xx status) and PostHogFetchNetworkError (fetch network error)
- I added `.on('error', (err) => void)` to the API
- I made shutdownAsync ignore fetch errors. They should be handled with `.on('error', ...)` from now on.
- I fixed `retriable` by only delaying when multiple tries are needed
- Fixed fetch compatibility by aligning error handling
- Added two errors: PostHogFetchHttpError (non-2xx …
> Improve error handling and make fetch error handling behave like fetch

- posthog-node/CHANGELOG.md
- posthog-node/package.json
- posthog-react-native/CHANGELOG.md
- posthog-react-native/package.json
- posthog-web/CHANGELOG.md
- posthog-web/package.json
Updates versions after [this PR](https://github.com/PostHog/posthog-js-lite/pull/88)
> Updated changelogs and versions

- posthog-core/src/index.ts
- posthog-core/test/posthog.featureflags.spec.ts
- posthog-core/test/posthog.groups.spec.ts
- posthog-core/test/posthog.identify.spec.ts
- posthog-node/test/posthog-node.spec.ts
- posthog-react-native/CHANGELOG.md
- posthog-react-native/package.json
- posthog-react-native/src/posthog-rn.ts
- posthog-react-native/src/storage.ts
- posthog-react-native/test/init.spec.ts
- posthog-web/CHANGELOG.md
- posthog-web/package.json
- posthog-web/src/posthog-web.ts
- posthog-web/test/posthog-web.spec.ts
Customer noticed that there seemed to be some ID issues despite using `PostHog.initAsync`. Investigated and found that the issue is happening as we don't wait for the async storage to be loaded _before_ we init PostHog and in turn call the reload.
* Changes `.initAsync` to warn if the SDK has already been initialised
* Moves the preload await to _before_ instantiating PostHog which ensures the correct IDs are loaded
* Handles the preloading of FF in the RN constructor to ensure we definitely don't accidentally load too early
- Fixes a race condition that could occur when initialising PostHog
- Fixes an issue where feature flags would not be reloaded after a reset
- (RN): PostHog should always be initialized via `.initAsync` and will now warn if this is not the case.
> fix: Race conditions when initialising the RN SDK

- posthog-node/package.json
- posthog-node/src/feature-flags.ts
- posthog-node/src/types/rusha.d.ts
- posthog-node/tsconfig.json
- yarn.lock
Replaces `crypto.createHash` with `rusha.createHash`, which is pure JS and thus compatible with Cloudflare Workers, and also making it work in the Next.js edge runtime.
I also checked that `crypto.createHash` and `rusha.createHash` create the same output.
Fixes #67
I added `rusha` from https://github.com/srijs/rusha
- Replace sha1 library with pure JS implementation
> Add pure JS sha1 library

- posthog-core/src/index.ts
- posthog-core/test/posthog.register.spec.ts
- posthog-react-native/CHANGELOG.md
- posthog-react-native/package.json
- posthog-react-native/src/posthog-rn.ts
- posthog-react-native/test/posthog.spec.ts
Customer brought up that autocapture events would be way more useful with the current screen name available.
* Registers the $screen_name whenever screen is called for subsequent events
- The `$screen_name` property will be registered for all events whenever `screen` is called
> feat: Save the $screen_name on every event

- posthog-core/src/index.ts
- posthog-core/src/types.ts
- posthog-react-native/src/posthog-rn.ts
- posthog-react-native/test/posthog.spec.ts
- tsconfig.json
Fixes https://github.com/PostHog/posthog-js-lite/issues/107
~Note: please merge https://github.com/PostHog/posthog-js-lite/pull/109 first, as this depends upon that.~
Adds these events that were present in v1. I put it behind an options flag, so that users will need to opt-in. This will prevent people from getting an unexpected surge of these events when updating the sdk.
Note: I found that due to ignoring the returned promise on line https://github.com/PostHog/posthog-js-lite/blob/54178fc167362f550c7f5703f2931abc487f8134/posthog-react-native/src/posthog-rn.ts#L108 , `initAsync` would return before `setupAsync` had completed. This is something that is a bit awkward to get right, when there in a constructor which needs to do something async. I fixed this by storing the promise and awaiting …
> feat: Add react native autocapture lifecycle events

- posthog-react-native/CHANGELOG.md
The latest entry/release is 2.7.1 https://github.com/PostHog/posthog-js-lite/releases/tag/posthog-react-native-v2.7.1
The 2.7.0 release was on April 21 https://github.com/PostHog/posthog-js-lite/releases/tag/posthog-react-native-v2.7.0
- [X ] Patch
No need.
> Fix changelog entries RN

- posthog-react-native/CHANGELOG.md
- posthog-react-native/src/hooks/useFeatureFlag.ts
Enabling feature flags with payload, this should be essential to have...
Enables feature flags with payload for react native
It just exposes a new hook for this.
- Added support for feature flags payload for react native useFeatureFlagWithPayload
> Added useFeatureFlagWithPayload for react native

- posthog-react-native/CHANGELOG.md
- posthog-react-native/package.json
Cut 2.8.0 release
https://github.com/PostHog/posthog-js-lite#publishing-a-new-version
Based on that, that's all I need to do, right?
> Release 2.8.0

- .github/workflows/ci.yml
- posthog-core/src/index.ts
- posthog-react-native/CHANGELOG.md
- posthog-react-native/package.json
- posthog-react-native/src/posthog-rn.ts
Might fix https://github.com/PostHog/posthog-js-lite/issues/117
Seems like we have some weird typing import issues that happened.  Not sure why or how, so need to validate this and ideally add a test...
> fix: Type issue with RN

- examples/example-node/yarn.lock
- posthog-node/CHANGELOG.md
- posthog-node/package.json
- yarn.lock
Fixes https://github.com/PostHog/posthog-js-lite/issues/121
User mentioned our axios dep is somewhat outdated. The vulnerability mentioned shouldn't affect us given we only call our own endpoint, but nonetheless worth keeping up to date.
Tested locally with the example and all seemed fine
> chore: Upgrade axios dep

- .github/CODEOWNERS
- .github/ISSUE_TEMPLATE/config.yml
- .github/ISSUE_TEMPLATE/maintainer-blank.yml
- .github/dependabot.yml
I have to check every PR to see if there's anything related to RN
Allowing empty issues/PRs usually allows low barriers and low-quality descriptions.
GH Actions have to be manually upgraded
RN PRs automatically assigned to me
Only allow using PR and Issues templates, blank just for PH people.
> GH codeowner for RN

- RELEASING.md
There are no releasing instructions
Add releasing instructions
> Add releasing markdown with releasing instructions

- posthog-core/src/index.ts
- posthog-react-native/CHANGELOG.md
- posthog-react-native/package.json
- posthog-web/CHANGELOG.md
- posthog-web/package.json
[Someone pointed out](https://github.com/PostHog/posthog-js/issues/917) that the posthog-js methods aren't available in RN. They are actually there just with slightly outdated naming
* Updates the naming to match
- Renamed `personProperties` to `setPersonPropertiesForFlags` to match `posthog-js` and more clearly indicated what it does
- Renamed `groupProperties` to `setGroupPropertiesForFlags` to match `posthog-js` and more clearly indicated what it does
> fix: Renamed some properties to match posthog-js

- posthog-core/src/index.ts
fix: logging typo from `enable` to `optIn`
Relates to https://github.com/PostHog/posthog-js-lite/issues/133
> fix: logging typo from `enable` to `optIn`

- posthog-react-native/src/posthog-rn.ts
This resolved #133 
- Resolved #133
> Use ?? instead of || in getPersistedProperty

- posthog-react-native/CHANGELOG.md
- posthog-react-native/package.json
Add changelog and cut new version
- `getPersistedProperty` uses Nullish Coalescing operator to fallback to `undefined` only if the property is not found
> Add changelog to Release 2.9.1 - RN

- posthog-node/CHANGELOG.md
- posthog-node/package.json
- posthog-node/src/feature-flags.ts
- posthog-node/src/posthog-node.ts
Reported issues where failing API requests can crash the process ([see here](https://posthog.com/questions/catching-error-on-initialization-in-node-js))
Don't throw but rather report up to the emitter
> fix: Unhandled error when background fetching flags

- posthog-core/package.json
- posthog-node/package.json
- posthog-react-native/package.json
- posthog-web/package.json
Tools such as Renovate can use the repository field to point to changes in new releases; posthog-node's repository field was out of date, causing Renovate to link to [the old 1.x repository](https://github.com/posthog/posthog-node).
Update package.json repository fields. See https://docs.npmjs.com/cli/v6/configuring-npm/package-json#repository
- Update package.json repository fields
> Update package.json repository fields

- posthog-react-native/CHANGELOG.md
- posthog-react-native/src/native-deps.tsx
- posthog-react-native/src/types.ts
- posthog-react-native/test/posthog.spec.ts
Closes https://github.com/PostHog/posthog-js-lite/issues/135
Helps with https://github.com/PostHog/posthog/issues/19341
> chore: `$device_type` is now set to `Mobile`, `Desktop` or `Web` for all events

- posthog-core/test/test-utils/test-utils.ts
- posthog-node/src/feature-flags.ts
- posthog-node/src/posthog-node.ts
- posthog-node/test/posthog-node.spec.ts
Made some changes but pulled them to a PR as I'm not so sure about them
@neilkakkar:
* Changes some of the expectations so that the payload for feature flag properties is always the same, regardless of source - worth checking if this is correct
* Fixes a bad issue with the `waitForPromises` that probably caused a lot of confusion elsewhere so hopefully thats an improvement
* This makes every `capture` call a promise but simplifies the logic and makes it more reliable which feels better
> fix: local props refactor

- posthog-node/CHANGELOG.md
- posthog-node/package.json
- posthog-node/src/feature-flags.ts
- posthog-node/test/feature-flags.spec.ts
rough copy of https://github.com/PostHog/posthog-python/pull/105/ 
> feat(flags): Add relative date operators, fix numeric ops

- posthog-core/src/index.ts
- posthog-core/test/test-utils/test-utils.ts
- posthog-node/CHANGELOG.md
- posthog-node/package.json
- posthog-node/src/feature-flags.ts
- posthog-node/src/posthog-node.ts
- posthog-node/test/extensions/sentry-integration.spec.ts
- posthog-node/test/feature-flags.spec.ts
- posthog-node/test/posthog-node.spec.ts
Copy of https://github.com/PostHog/posthog-python/pull/106/
This turned out to be a lot trickier than expected, because I noticed a few issues. With the `sendFeatureFlags` capture option, it seems like we were dropping events, since on shutdown the feature flag promises aren't tracked for populating flag information, which means the capture is not enqueued.
I can't yet think of a better way to solve this right now, so we just start tracking flag promises from within capture as well, annnd flush again on shutdown after pending promises have resolved, to make sure all new capture events queued are sent as well.
I'm also moving a few more things that should've been based on the onError emitter, and fixed tests that incorrectly assumed this was working fine.
(cc: @marandaneto @benjackwhite …
> feat(flags): Add local props and flags to all calls

- README.md
Releasing instructions is moved to https://github.com/PostHog/posthog-js-lite/blob/main/RELEASING.md md.
> Update README.md about Releasing instructions

- posthog-react-native/CHANGELOG.md
- posthog-react-native/src/native-deps.tsx
- posthog-react-native/src/optional/OptionalExpoFileSystem.ts
- posthog-react-native/src/optional/OptionalReactNativeDeviceInfo.ts
fix: if react-native-device-info is available for the Web target, do not set unknown for all properties
Relates to https://github.com/PostHog/posthog-js-lite/issues/140
> fix: if react-native-device-info is available for the Web target, do not set unknown for all properties

- posthog-react-native/CHANGELOG.md
- posthog-react-native/src/optional/OptionalExpoFileSystem.ts
fix: Do not try to load the expo-file-system package on the Web target since it's not supported
If the `expo-file-system` target is installed on RN Web, the module is loaded but its methods aren't supported leading to errors.
Closes https://github.com/PostHog/posthog-js-lite/issues/140
> fix: Do not try to load the expo-file-system package on the Web target since it's not supported

- posthog-core/src/index.ts
- posthog-core/src/types.ts
- posthog-core/test/posthog.capture.spec.ts
- posthog-core/test/posthog.identify.spec.ts
- posthog-node/CHANGELOG.md
- posthog-node/package.json
- posthog-node/src/posthog-node.ts
- posthog-node/src/types.ts
- posthog-node/test/extensions/sentry-integration.spec.ts
- posthog-node/test/posthog-node.spec.ts
- posthog-react-native/CHANGELOG.md
- posthog-react-native/package.json
- posthog-react-native/src/posthog-rn.ts
- posthog-react-native/src/types.ts
- posthog-web/CHANGELOG.md
- posthog-web/package.json
Some people want to override the eventId to do things like deduplication
* Adds a default uuid
* Accepts the override option
- Added the ability to override the event ID via the extra options argument in capture calls
> feat: Add eventId overriding options

- .eslintrc.js
- .prettierignore
- examples/example_rn/Makefile
- posthog-core/src/index.ts
- posthog-core/src/vendor/uuidv7.ts
- posthog-core/test/posthog.capture.spec.ts
- posthog-react-native/CHANGELOG.md
- posthog-react-native/package.json
The RN publish cmd isn't copying the peer dependencies correctly.
After fixing this, there was an issue with the `crypto` package which is `node` only.
Loading packages dynamically on RN is better with `Platform.select` otherwise it causes issues on macOS/Web, etc.
`Platform.select` is only available on React Native, so we cannot use it on the core package.
The best solution was to vendor the `uuidv7` which is apache2 anyway and let `getDefaultRandom` use only the `Math.random` available on all platforms.
Only affects RN because `crypto` was available on the other env.
Vendor `uuidv7`
> Fix: [React Native] - Vendor uuidv7 instead of using peer dependency to avoid the missing crypto issue

- posthog-react-native/CHANGELOG.md
- posthog-react-native/src/native-deps.tsx
https://github.com/PostHog/posthog-js-lite/pull/172/files#r1481614909
> fix: app_build was returning the OS internal build number instead of the app's build number

- posthog-react-native/src/posthog-rn.ts
The recommended way to set up PostHog for React Native is to use the PostHogProvider. Indeed that is true
However while using it like that we are facing console warning which annoys and distracts from really important things.
Folks [here](https://github.com/PostHog/posthog-js-lite/issues/114) already reported about this problem
Just removed console.warn. It more harms than helps, you already did a great job to prevent re-initialization, so I don't think that warning helps
- Removed "PostHog.initAsync called twice with the same apiKey" console warning
> chore: remove PostHog.initAsync warning

- posthog-react-native/CHANGELOG.md
- posthog-react-native/src/PostHogProvider.tsx
See https://github.com/PostHog/posthog-js-lite/issues/182
Potentially the issue comes from a race condition with other SDKs patching the global Promise object in a way that breaks the `instanceof` check.
* Swaps to use a simpler ".then" check instead which is more than good enough for our use case.
(Added)
> fix: Promise comparison issue

- posthog-core/src/index.ts
- posthog-core/src/types.ts
- posthog-core/src/utils.ts
- posthog-node/src/posthog-node.ts
There was a mismatch of the default retry timeout depending on the code path.
> chore: add retry default comments and fix misconfig default

- posthog-core/src/index.ts
- posthog-core/src/utils.ts
- posthog-react-native/CHANGELOG.md
- posthog-react-native/src/native-deps.tsx
- posthog-react-native/src/posthog-rn.ts
- posthog-react-native/src/storage.ts
- posthog-react-native/src/types.ts
- posthog-react-native/test/posthog.spec.ts
- posthog-react-native/test/storage.spec.ts
Tempt to fix https://github.com/PostHog/posthog-js-lite/issues/96
> chore: ref to allow sync storage friendlier

- posthog-core/src/index.ts
- posthog-core/src/types.ts
- posthog-node/CHANGELOG.md
- posthog-node/src/posthog-node.ts
- posthog-react-native/CHANGELOG.md
- posthog-web/CHANGELOG.md
^^ We want a much shorter timeout on flags, since they can block client applications. Also makes this configurable now.
Fixes https://github.com/PostHog/posthog-js-lite/issues/195
> fix(flags): Add a shorter timeout, disable retries for flags

- posthog-node/CHANGELOG.md
- posthog-node/package.json
- posthog-react-native/CHANGELOG.md
- posthog-react-native/package.json
- posthog-web/CHANGELOG.md
- posthog-web/package.json
> chore: release next major beta-1

- .github/workflows/bundle-size.yml
- .github/workflows/ci.yml
spotted the bundle checker wasn't actually checking anything
RN outputs a lot of files,
posthog-node do we care?
fixed the checker and restricted it to only posthog-web
> chore(ci): fix bundle checker

- posthog-node/CHANGELOG.md
- posthog-node/package.json
- posthog-react-native/CHANGELOG.md
- posthog-react-native/package.json
- posthog-web/CHANGELOG.md
- posthog-web/package.json
Another beta since there were no tests nor reports from customers, no more changes expected either, after this one, we can cut a stable version.
> chore: release next major beta.2

- posthog-react-native/CHANGELOG.md
- posthog-react-native/src/PostHogProvider.tsx
A regression introduced by #189 requires a client and apiKey to initialize a PostHogProvider even though the error message says only one is required.
The error condition logic is fixed and a non null assertion is made.
- Fix: PostHogProvider initialization
> fix: PostHogProvider initialization logic

- posthog-node/CHANGELOG.md
- posthog-node/package.json
- posthog-react-native/CHANGELOG.md
- posthog-react-native/package.json
Releases https://github.com/PostHog/posthog-js-lite/pull/206 and https://github.com/PostHog/posthog-js-lite/pull/205
> chore: release node v4 beta 3 and rn v3 beta 3

- posthog-react-native/CHANGELOG.md
- posthog-react-native/src/frameworks/wix-navigation.ts
- posthog-react-native/src/hooks/useLifecycleTracker.ts
- posthog-react-native/src/posthog-rn.ts
- posthog-react-native/test/posthog.spec.ts
Closes https://github.com/PostHog/posthog-js-lite/issues/144
https://posthoghelp.zendesk.com/agent/tickets/11961
Depend on the SDK config, the dashboard should use different event names, its better to align that within the SDK
Technically a breaking change but I don't see many people using `captureNativeAppLifecycleEvents` anyways, it's written in the changelog.
It's hard for support to figure out the multiple scenarios depending on the SDK configuration.
Our mobile dashboard templates don't even consider the `from_background` property anyway, so now using this config (captureNativeAppLifecycleEvents) will match our templates.
Added the app version and build to the other integrations.
> chore: Change Application opened to application became active for native events

- posthog-core/package.json
- yarn.lock
its vendored already https://github.com/PostHog/posthog-js-lite/blob/main/posthog-core/src/vendor/uuidv7.ts
the dep was just an oversight
> fix: remove uuidv7 dep since its vendored

- examples/example_expo_rn_web/App.tsx
- examples/example_rn/posthog.tsx
- examples/example_rn_macos/App.tsx
- examples/example_rn_new_architecture/App.tsx
- posthog-core/src/index.ts
- posthog-core/src/types.ts
- posthog-core/test/posthog.capture.spec.ts
- posthog-core/test/posthog.featureflags.spec.ts
- posthog-core/test/posthog.init.spec.ts
- posthog-node/CHANGELOG.md
- posthog-node/src/extensions/sentry-integration.ts
- posthog-react-native/CHANGELOG.md
- posthog-web/CHANGELOG.md
- posthog-web/test/posthog-web.spec.ts
still using the older endpoint https://app.posthog.com/
default endpoint is https://us.i.posthog.com
> chore: change host to new address.

- posthog-web/CHANGELOG.md
- posthog-web/src/storage.ts
Usage in the browser will always fallback to session storage rather than localstorage due to a simple logical conditional error.
When local storage is available it should be used when requested before falling back to sessionstorage.
Corrects faulty condition so availability of local storage is evaluated correctly
- use localstorage over sessionstorage where available
> fix: should attempt localstorage correctly before falling back to session storage

- posthog-node/CHANGELOG.md
- posthog-node/package.json
- yarn.lock
Addressing https://github.com/PostHog/posthog-js-lite/issues/246 and https://github.com/PostHog/posthog-js-lite/security/dependabot/112
> chore(deps): bump axios to 1.7.4

- posthog-node/src/feature-flags.ts
- posthog-node/test/feature-flags.spec.ts
The current behavior of stringifying `undefined` and `null` values to compare with operators can lead to invalid results in local evaluation. 
This causes local evaluation to return `true`, while the `/decide` API does the right thing and returns false for `undefined` values in these properties.  
Customer reported that local evaluation always evaluates a condition to true, when it should evaluate to false. 
The conditions in question are : 
``` json
[
{
"key": "latestBuildVersion",
"type": "person",
"value": ".+",
"operator": "regex"
},
{
"key": "latestBuildVersionMajor",
"type": "person",
"value": "23",
"operator": "gt"
},
{
"key": "latestBuildVersionMinor",
"type": "person",
"value": "31",
"operator": "gt"
},
{
"key": "latestBuildVersionPatch",
"type": "person",
"value": "0", …
```
> fix(feature flags) : Local evaluation : guard for null values when comparing person Properties

- posthog-node/CHANGELOG.md
- posthog-node/package.json
- posthog-node/src/feature-flags.ts
- posthog-node/test/feature-flags.spec.ts
Bump `posthog-node` to `4.1.1`
> chore(posthog-node): bump version to 4.1.1

- posthog-core/src/index.ts
- posthog-core/src/types.ts
- posthog-node/CHANGELOG.md
- posthog-node/package.json
We have an optimisation flag for historical migrated data documented here but we don't expose a way of configuring it.
* Adds the option
> feat: Added historical migration option

- examples/example_expo_rn_web/App.tsx
- posthog-core/src/index.ts
- posthog-core/src/types.ts
- posthog-core/test/posthog.capture.spec.ts
- posthog-core/test/posthog.flush.spec.ts
- posthog-core/test/posthog.shutdown.spec.ts
- posthog-core/test/test-utils/test-utils.ts
- posthog-node/CHANGELOG.md
- posthog-node/src/posthog-node.ts
- posthog-react-native/CHANGELOG.md
- posthog-web/CHANGELOG.md
https://posthog.slack.com/archives/C04MZFDA5KK/p1724686090270609?thread_ts=1724403501.407719&cid=C04MZFDA5KK
> chore: change captureMode to json

- examples/example-expo-latest/package.json
- examples/example_rn/package.json
- posthog-react-native/CHANGELOG.md
- posthog-react-native/package.json
- posthog-react-native/src/posthog-rn.ts
- yarn.lock
Depends on https://github.com/PostHog/posthog-react-native-session-replay/pull/5/files
> fix: set the right sdk name and version for recordings

- posthog-react-native/src/optional/OptionalSessionReplay.ts
This brings the structure in line with the other optional dependencies, ensuring that logs stay quiet
When SessionReplay isn't installed, it produces a warning log. This is inconsistent with the other optional dependencies.
- Removed a warning log when posthog-react-native-session-replay is not installed
> Remove Debug Statement when SessionReplay doesn't load

- posthog-react-native/package.json
missed during merge conflict https://github.com/PostHog/posthog-js-lite/pull/259
> chore: change rn version to 3.3.3

- posthog-core/src/index.ts
- posthog-node/CHANGELOG.md
- posthog-node/package.json
- posthog-node/src/feature-flags.ts
- posthog-react-native/CHANGELOG.md
- posthog-react-native/package.json
- posthog-react-native/src/posthog-rn.ts
Closes https://github.com/PostHog/posthog-react-native-session-replay/issues/7
Only logs message if debug is enabled
> fix: only logging if debug enabled

- posthog-react-native/CHANGELOG.md
- posthog-react-native/package.json
- posthog-react-native/src/native-deps.tsx
Relates to https://posthoghelp.zendesk.com/agent/tickets/19293
Found a follow-up as well https://github.com/PostHog/posthog-js-lite/issues/286
Tries to read device context from Expo libs, if not available, tries to read from react-native-device-info, but not from both.
They overwrite each other values and just cause unnecessary issues.
> fix: only tries to read device context from react-native-device-info if expo libs are not available

- posthog-react-native/CHANGELOG.md
- posthog-react-native/package.json
- posthog-react-native/src/posthog-rn.ts
https://posthog.com/questions/installing-session-replay-and-updating-posthog-crashes-the-app
> fix: all sdkReplayConfig should have a default value

- posthog-web/README.md
See https://posthog.slack.com/archives/C03P7NL6RMW/p1729779075000879 - clarifies when to use it, and removes WIP tag - its somewhat misleading.
> Clarify posthog-js-lite messaging

- posthog-react-native/CHANGELOG.md
- posthog-react-native/package.json
- posthog-react-native/src/posthog-rn.ts
- posthog-react-native/src/types.ts
- yarn.lock
Relates to https://github.com/PostHog/posthog-react-native-session-replay/issues/10
> chore: change androidDebouncerDelayMs default from 500ms to 1000ms (1s)

- posthog-react-native/CHANGELOG.md
- posthog-react-native/package.json
- posthog-react-native/tsconfig.json
re https://github.com/PostHog/posthog-js-lite/pull/294#discussion_r1815663690
Closes https://github.com/PostHog/posthog-js-lite/issues/298 ?
Everything works locally just fine but that was the only change that could make that happen
> fix: rollback module to ESNext

- examples/example-expo-latest/App.tsx
- posthog-react-native/CHANGELOG.md
- posthog-react-native/package.json
- posthog-react-native/src/PostHogProvider.tsx
- posthog-react-native/src/autocapture.tsx
Closes https://github.com/PostHog/posthog-js-lite/issues/301
> fix: capture customLabelProp if set

- posthog-react-native/CHANGELOG.md
- posthog-react-native/package.json
- posthog-react-native/src/autocapture.tsx
follow up https://github.com/PostHog/posthog-js-lite/pull/302/files
> fix: respect the given propsToCapture autocapture option

- examples/example-expo-latest/package.json
- posthog-react-native/CHANGELOG.md
- posthog-react-native/package.json
- posthog-react-native/src/posthog-rn.ts
for some reason, sometimes but not so rarely, the recording does not have associated events but the SDK did capture events, and the session id does not match.
I believe the SDK can be already enabled or the session id rotated wrongly in the native SDK.
Now the hybrid SDK fully controls the session id lifecycle and if the SDK is somehow already enabled, we force the session id again.
Depends on https://github.com/PostHog/posthog-ios/pull/253 as well
> fix: session replay forces the session id if the SDK is already enabled

- posthog-core/src/index.ts
- posthog-core/test/posthog.shutdown.spec.ts
- posthog-node/CHANGELOG.md
- posthog-node/package.json
The shutdown timeout is misleading. If a fetch request is timing out we may still sit on it as we only do the check after it is done.
Change to a timeout based solution. It's a little complex but i think thats just _the way_.
- Shutdown will now respect the timeout and forcefully return rather than returning after the next fetch.
> fix: Enforce the shutdown timeout 

- examples/example-expo-latest/App.tsx
- examples/example-expo-latest/package.json
- examples/example_rn/package.json
- posthog-core/src/index.ts
- posthog-react-native/CHANGELOG.md
- posthog-react-native/package.json
- posthog-react-native/src/posthog-rn.ts
- yarn.lock
recordings are only flushed when flushAt is at 20 which is the default value on Mobile but not the given flushAt when intiting the RN SDK
Depends on https://github.com/PostHog/posthog-react-native-session-replay/pull/13
> fix: session replay respects the flushAt flag

- pnpm-lock.yaml
- posthog-node/pnpm-lock.yaml
- posthog-node/src/extensions/sentry-integration.ts
- posthog-node/test/extensions/sentry-integration.spec.ts
Our Sentry integration does not work for v8. Prompted by the great work in https://github.com/PostHog/posthog-js-lite/pull/243.
We already support v8 in `posthog-js` so I went about copying the approach used there and fixing any of the drift between the two implementations of the Sentry integration. Because of the way that the `posthog-node` package works the code isn't 100% equivalent but this works pretty well
- Added support for Sentry v8 integration
> chore: support Sentry v8

- posthog-node/CHANGELOG.md
- posthog-node/package.json
- posthog-node/src/posthog-node.ts
- posthog-node/src/types.ts
- posthog-node/test/posthog-node.spec.ts
Reverts PostHog/posthog-js-lite#315
> Revert "fix(flags): send `feature_flag_called` events with correct payload data in the event that we need to fetch the payloads from the server"

- posthog-react-native/CHANGELOG.md
- posthog-react-native/package.json
- posthog-react-native/src/native-deps.tsx
> fix: os_name was not being set correctly for some devices using expo-device

- posthog-node/test/feature-flags.spec.ts
- posthog-react-native/CHANGELOG.md
- posthog-react-native/package.json
- posthog-react-native/src/posthog-rn.ts
We are seeing constant logs about the replay session Id not being rotated and it appeared to be a something going wrong. In reality it seems that this was just meant to be debug info so I wrapped it in that flag. Upon closer inspection it seems that the currentSessionId will never have a value so this is now being set after the session replay starts with a session Id the first time.
1. Now setting a value to currentSessionId after session replay starts with one the first time.
2. Wrapped the log so its debug only.
- Fixed currentSessionId initialization and logging
> Set initial currentSessionId, log only with debug flag on.

- posthog-react-native/CHANGELOG.md
- posthog-react-native/package.json
- posthog-react-native/src/posthog-rn.ts
replay flags were not evaluated on the SDK level, now they are.
> fix: session replay respect linked feature flags

- posthog-ai/package.json
- posthog-ai/src/vercel/middleware.ts
some providers do not send back friendly names for the model or provider in vercel.
we can allow the user to specify these in those cases
add override params
> feat(ai): allow user to override values for model and provider

- posthog-react-native/CHANGELOG.md
- posthog-react-native/package.json
- posthog-react-native/src/posthog-rn.ts
Noticed errors in the production version of a React Native app, complaining of the line with a typecast. When the config is null, it goes through the `typeof ... === 'object'` condition, as `typeof` for null returns `object`.
Fix the line to check for null values.
- fix: improve session replay linked flag type handling
> fix(session-replay): improve session replay linked flag type handling

- examples/example_rn/package.json
- posthog-ai/src/anthropic/index.ts
- posthog-ai/src/vercel/middleware.ts
- posthog-react-native/CHANGELOG.md
- posthog-react-native/package.json
- posthog-react-native/src/native-deps.tsx
- posthog-react-native/src/optional/OptionalReactNativeLocalize.ts
- yarn.lock
Closes https://github.com/PostHog/posthog-js-lite/issues/286
> chore: set locale and timezone using the react-native-localize library

- posthog-node/test/feature-flags.spec.ts
This test was failing on my local machine because of TZ differences. Here's the breakdown.
1. System Date: `2022-05-01`. Jest interprets it as `2022-05-01 00:00:00 UTC`
2. 1hr before `2022-04-30 23:00:00 UTC`
3. Override value: `2022-04-30 22:00:00` which JavaScript interprets as PDT (I live on the west coast of the U.S.). Converted to UTC -> `2022-05-01 05:00:00 UTC`. That's definitely not before `2022-05-01 00:00:00 UTC` and the test fails.
Fix: Specify GMT for the override value.
Some of the other tests might break for other TZ. We should probably mock the TZ in the tests to be more explicit. But I just want to make these tests pass my machine for now.
> fix:Specify tz with the date

- posthog-core/test/posthog.featureflags.spec.ts
- posthog-node/CHANGELOG.md
- posthog-node/package.json
- posthog-node/src/posthog-node.ts
- posthog-node/test/feature-flags.spec.ts
- posthog-node/test/posthog-node.spec.ts
See https://github.com/PostHog/posthog-python/pull/181 for more context. This PR is a port of that fix.
The `client.getFeatureFlag()` method will by default call `client.capture` with the event named `$feature_flag_called`. 
Some time ago, the `capture()` method was changed to enrich the event with all locally cached feature flags even if `sendFeatureFlags` is `false`.
What this leads to is `client.getFeatureFlag()` -> `client.capture()` -> `client.getAllFlags()`. But the call to `client.getAllFlags()` isn't passed the original `person_properties` that were passed to `client.getFeatureFlag()`. This leads to inconsistency in the enriched data.
This PR takes the simplest path by not enriching the captured event with all feature flags for the `$feature_flag_called` event.
If the captured …
> Do not enrich the $feature_flag_called event with more feature flag data

- examples/example-node/example.ts
- examples/example-node/tsconfig.json
- posthog-node/CHANGELOG.md
- posthog-node/package.json
- posthog-node/src/feature-flags.ts
- posthog-node/src/posthog-node.ts
Context: [PostHog/posthog#27414 (files)](https://github.com/PostHog/posthog/pull/27414/files)
Adds new `getDecryptedFeatureFlagPayload` method to Node SDK
> feat(flags): Add method for fetching decrypted remote config flag payload

- posthog-core/src/index.ts
- posthog-react-native/CHANGELOG.md
- posthog-react-native/package.json
Closes https://github.com/PostHog/posthog-js-lite/issues/391
> fix: ensure feature flags are reloaded after reset() to prevent undefined values

- posthog-core/src/index.ts
- posthog-core/test/posthog.ai.spec.ts
- posthog-node/CHANGELOG.md
- posthog-node/package.json
- posthog-react-native/CHANGELOG.md
- posthog-react-native/package.json
- posthog-web/CHANGELOG.md
- posthog-web/package.json
It should be straightforward to capture a LLM metric or feedback.
- Add methods to capture user feedback and metrics.
- Convert values like numbers and booleans to strings to unify the property type.
@k11kirky please check the naming. I thought about `captureAIFeedback`, but I don't like three capital letters in a row. `captureFeedback` and `captureMetric` are probably too generic.
- Added `captureTraceMetric` and `captureTraceFeedback` methods for LLM Observability.
> feat(llm-observability): metric and feedback methods

- examples/example-expo-latest/App.tsx
- posthog-react-native/CHANGELOG.md
- posthog-react-native/package.json
- posthog-web/CHANGELOG.md
- posthog-web/package.json
Follow up https://github.com/PostHog/posthog-js-lite/pull/403
changes were for web and RN as well
> chore: release Supports gracefully handling quotaLimited responses from the PostHog API for feature flag

- posthog-core/src/index.ts
- posthog-core/src/types.ts
- posthog-node/CHANGELOG.md
- posthog-node/package.json
- posthog-node/src/posthog-node.ts
To help correlate Node SDK (remotely loaded) $feature_flag_called events to `/decide` requests, we'll attach  a new `$feature_flag_request_id` property to the event
Combined with https://github.com/PostHog/posthog/pull/29563, we'll have clear signal as to how a specific flag evaluation was determined at a point in the past, including any SDK property overrides that could have affected it.
- Refactor stateless flag code to return both a flag value and a requestId, if one is found
- Add the `$feature_flag_request_id` property to $feature_flag_called event
Request ID being passed through with https://github.com/PostHog/posthog/pull/29563 changes:
SDK just omits `$feature_flag_request_id` if none present in API response:
> feat(flags): Attach requestId to $feature_flag_called if present in /decide response

- examples/example-expo-latest/App.tsx
- posthog-core/src/index.ts
- posthog-react-native/src/posthog-rn.ts
we're doing it for decide API but not for remote config
> fix: cache replay config for remote config

- posthog-node/CHANGELOG.md
- posthog-node/src/feature-flags.ts
We weren't handling backing off on 429s, so we kept hammering the `fetch` if a request was rate-limited.
Added an error handler that wraps 429 errors in exponential backoffs (like we do with 401 and 403 errors)
- Fix: prevent fetch floods when quota limited.
> fix: update the rate-limiting logic to ensure we don't repeatedly fetch

- posthog-core/src/index.ts
- posthog-node/CHANGELOG.md
- posthog-node/test/posthog-node.spec.ts
- posthog-node/test/test-utils.ts
Customer asked for this, seems reasonable to do it: https://posthog.slack.com/archives/C0386ASS3TN/p1742599095502899?thread_ts=1740762972.509389&cid=C0386ASS3TN
> chore(flags): emit an error message whenever `/decide` fails to calculate flags

- posthog-node/CHANGELOG.md
- posthog-node/package.json
- posthog-node/src/posthog-node.ts
- posthog-node/test/feature-flags.decide.spec.ts
- posthog-node/test/feature-flags.spec.ts
- posthog-node/test/posthog-node.spec.ts
- posthog-node/test/test-utils.ts
A feature flag might not exist in a `/decide` response for three reasons.
1. It never existed.
2. It was deleted.
3. It had an error during evaluation
In the third case, returning `true` when there was an error was confusing. In all cases, the value of the flag is indeterminate so it makes sense to return `undefined`.
No longer coerces `undefined` flag value to `false`.
- `getFeatureFlag` and `isFeatureEnabled` now return `undefined` when the flag is not in the response.
> fix(flags): Return undefined when a feature flag does not exist

- posthog-core/src/patch.ts
- posthog-core/src/utils.ts
- posthog-web/CHANGELOG.md
- posthog-web/README.md
- posthog-web/src/posthog-web.ts
- posthog-web/src/types.ts
- posthog-web/test/posthog-web.spec.ts
This Bluesky thread gave us the idea: https://bsky.app/profile/danabra.mov/post/3lmflnn62ys2y to have a tiny sdk option for simple navigation event capture.
This internal Slack thread also has some comments, it is my first SDK PR: https://posthog.slack.com/archives/C03P7NL6RMW/p1744225093576939
I've bundled a simple repo to test this out: https://lricoy.github.io/test-posthog-history/
Added an option to attach listeners to the browser's history api and autocapture pageviews.
- Added `trackHistoryEvents` option to automatically capture navigation events in single-page applications using the History API.
> feat: add autocapture pageviews with history api

- posthog-react-native/CHANGELOG.md
- posthog-react-native/package.json
- posthog-react-native/src/PostHogProvider.tsx
- posthog-react-native/src/hooks/useNavigationTracker.ts
- posthog-react-native/src/types.ts
Fixes https://github.com/PostHog/posthog-js-lite/issues/450
```
import { createNavigationContainerRef } from '@react-navigation/native'
export const navigationRef = createNavigationContainerRef()
```
Check the new autocapture prop `navigationRef`
```
export default function RootLayout() {
const colorScheme = useColorScheme()
const [loaded] = useFonts({
SpaceMono: require('../assets/fonts/SpaceMono-Regular.ttf'),
})
useEffect(() => {
if (loaded) {
SplashScreen.hideAsync()
}
}, [loaded])
if (!loaded) {
return null
}
return (
<PostHogProvider
client={posthog}
autocapture={{
captureScreens: true,
captureLifecycleEvents: true,
captureTouches: true,
navigationRef: navigationRef,
}}
>
<ThemeProvider value={colorScheme === 'dark' ? DarkTheme : DefaultTheme}>
<Stack ref={navigationRef}> …
```
> fix: react native navigation missing navigationRef

- posthog-node/package.json
- posthog-node/src/extensions/error-tracking/error-conversion.ts
- posthog-node/test/extensions/error-conversion.spec.ts
- yarn.lock
- The error cause is not use used when building a stacktrace
See: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error/cause
- Add support for it
- Added support for error cause
> feat(err): support for error causes

- examples/example-node/server.ts
- posthog-node/src/feature-flags.ts
- posthog-node/src/posthog-node.ts
- posthog-node/src/types.ts
- posthog-node/test/feature-flags.spec.ts
This PR provides a way for users to determine if feature flag definitions for local evaluation are loaded.
Fixes #445
This adds a new `waitForLocalEvaluationReady` method that waits up to 30 seconds (configurable) for local evaluation feature flags to be loaded.
* It returns `true` immediately if flags are already loaded.
* It returns `false` immediately if local evaluation is not enabled.
This new method waits for the new `localEvaluationFlagsLoaded` event which is emitted when we retrieve feature flag definitions from the local evaluation endpoint.
This PR also adds a synchronous `isLocalEvaluationReady()` method that checks the feature flag poller to see if any flags are loaded.
- Added new `waitForLocalEvaluationReady()` method used to wait for local evaluation flags to be loaded.
- …
> feat: Add method to wait for feature flag definitions for local evaluation to be loaded.

- README.md
- posthog-node/CHANGELOG.md
- posthog-node/package.json
This is a follow-up to https://github.com/PostHog/posthog-js-lite/pull/447
> chore: Bump posthog-node to 4.13.0

- examples/example-cloudflare/src/index.ts
- examples/example-gcp-functions/index.js
- posthog-core/src/index.ts
- posthog-core/test/posthog.shutdown.spec.ts
- posthog-node/src/posthog-node.ts
Calling shutdown multiple times can have an unexpected result. Additionally, we tell people to do this in our docs.
Guard shutdown with a shared promise, similar to how we handle flush. Doesn't break anything if people are calling shutdown() per-request, but also gives them a debug log (and a comment) telling them not to do this
- Added protection against calling shutdown in parallel, and update examples to be clearer on using flush() rather than shutdown() for serverless use-cases.
> fix: Add a guard around calling shutdown multiple times

- posthog-ai/src/utils.ts
- posthog-core/src/index.ts
- posthog-core/src/utils.ts
- posthog-core/test/posthog.flush.spec.ts
- posthog-core/test/posthog.groups.spec.ts
- posthog-core/test/posthog.identify.spec.ts
- posthog-core/test/test-utils/PostHogCoreTestClient.ts
- posthog-core/test/test-utils/test-utils.ts
- posthog-node/test/posthog-node.spec.ts
- posthog-node/test/test-utils.ts
There's a long internal thread here: https://posthog.slack.com/archives/C087XQ7K9K7/p1745963996974469
We are not respecting the maximum body size restrictions on the capture endpoint, and `flush()` does not correctly flush all events.
* Handle 413 errors, which can be returned if the request is too large. Handle this by reducing the batch size by half and retrying. If batch size was already 1, treat it as a regular error.
* Change the behaviour of `flush()`, to send >1 batch if necessary. Previously, it only sent 1 batch
* Ensure that `flush()` does not get stuck infinitely if there are a constant stream of new events. It is only guaranteed to flush events that occurred before `flush()` was called (and *may* include some afterwards, but is not guaranteed to) or until an error occurred.
- …
> fix: Improve flush behaviour

- .github/workflows/bundle-size.yml
- posthog-node/.npmignore
- posthog-node/CHANGELOG.md
- posthog-node/package.json
- rollup.config.js
Related to : https://github.com/PostHog/posthog-js-lite/issues/491
- Module types are not detected correcly
- Give filenames explicit types
- Fix tsup bundling
> fix(posthog-node): give explicit file types

- posthog-ai/CHANGELOG.md
- posthog-ai/package.json
- posthog-web/CHANGELOG.md
- posthog-web/package.json
- rollup.config.js
Reported in https://github.com/PostHog/posthog-js-lite/issues/491#issuecomment-2853781601
Apply same fixes to the web / ai repos that were added to Node in https://github.com/PostHog/posthog-js-lite/pull/492
- Fix exported file extensions to work with older Node versions
> fix: correct file export names

- posthog-react-native/package.json
forgot to modify the version so release was skipped in the CI pipeline
> chore: release 3.15.3

- posthog-core/src/index.ts
We have callbacks to notify user code of failure, crashing user apps is a non-starter
> fix: no throw in sendImmedate

- posthog-node/package.json
- posthog-node/src/extensions/error-tracking/chunk-ids.ts
- posthog-node/src/extensions/error-tracking/error-conversion.ts
- posthog-node/src/extensions/error-tracking/types.ts
- When minifying js code for server use, there is no way to get error context. It generally happen when using nextjs SSR, server actions and so on... 
- Add chunk id to stack frames
- Add support for node minified sources inside error tracking
> feat(err): add chunk id to posthog-node frames

- posthog-react-native/CHANGELOG.md
- posthog-react-native/package.json
- posthog-react-native/src/posthog-rn.ts
Helps with https://github.com/PostHog/posthog-js-lite/issues/510
iOS will stop capturing network logs and console logs in the background, so the React Native sessions should not be extended because of this after those changes.
Android does not capture network logs for React native yet.
afaict console logs on Android aren't captured when the app is in the background.
> rotate session id if expired when the app is back from background

- posthog-ai/CHANGELOG.md
- posthog-ai/package.json
This has just been released, let's use it as our dependency to foster adoption
> chore: Use `posthog-node` v5.0.0

- posthog-core/package.json
- posthog-react-native/package.json
- posthog-web/package.json
People who are creating a bill of materials (BOM) for their project often analyse the package.json files of their dependencies to see what the licenses of the libraries they're depending on, so it's useful to them to have `license` fields in `package.json` files of distributed packages.
I've added `"license": "MIT"` to `package.json` files that didn't have it. This matches the license of the repository and the `license` field in some of the other `package.json` files.
- Added support for package.json `license` field.
> add missing `license` field to package.json files

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/pull_request_template.md
- .github/workflows/release.yml
- package.json
- posthog-nextjs/.npmignore
- posthog-nextjs/CHANGELOG.md
- posthog-nextjs/README.md
- posthog-nextjs/package.json
- posthog-nextjs/src/config.ts
- posthog-nextjs/src/index.ts
- posthog-nextjs/src/webpack-plugin.ts
- posthog-nextjs/tsconfig.json
- rollup.config.js
- Configure sourcemaps generation for nextjs
- Upload sourcemaps during build process
- Configure sourcemaps generation for nextjs
- Upload sourcemaps during build process
> feat(nextjs): create @posthog/nextjs package

- examples/example-expo-latest/package.json
- examples/example_rn/package.json
- posthog-react-native/CHANGELOG.md
- posthog-react-native/package.json
- posthog-react-native/src/posthog-rn.ts
- yarn.lock
follow up https://github.com/PostHog/posthog-react-native-session-replay/pull/30/files
> chore: force session replay to use string values for sessionId, distinctId and anonymousId

- posthog-node/CHANGELOG.md
- posthog-node/package.json
- posthog-node/src/client.ts
- posthog-node/src/extensions/feature-flags/feature-flags.ts
- posthog-node/src/types.ts
- posthog-node/test/posthog-node.spec.ts
We have this problem with our server-side SDKs where we start the feature flag poller (for local evaluation) as soon as customers supply a `personalApiKey`.  This led to reports (e.g.: https://posthog.slack.com/archives/C04J1TJ11UZ/p1751499805232469) where customers were mentioning not wanting to pay for local eval when their goal for supplying the personal API key was to just use the `getRemoteConfigPayload` method.
Coupling the personal API key to feature flag polling is an artifact of when the only reason to supply a personal API key to the posthog-node library was to do local eval, but now that it's used for at least remote config decryption (and possibly more things), I think it makes sense to decouple those components.
- decoupled `getRemoteConfigPayload` from the feature flag …
> feat(flags): decouple local evaluation from personal API keys; support decrypting remote config payloads without relying on the feature flags poller

- posthog-node/CHANGELOG.md
- posthog-web/CHANGELOG.md
PostHog web now attempts to compress messages with GZip before sending them to our servers if available in your runtime. This shouldn't cause you any problems, but if someone's tests are attempting to assert on the data that's sent to our servers, they'll now need to decompress it first.
Let's note this on the BREAKING CHANGES section of both our web and node versions
See https://github.com/PostHog/posthog-js-lite/pull/481
> docs: Add CHANGELOG notice about GZip compression

- posthog-node/src/extensions/feature-flags/feature-flags.ts
- posthog-node/test/feature-flags.spec.ts
Add support for the new "flag" filter type to prevent serialization errors during local feature flag evaluation. Flag dependencies are not yet implemented in local evaluation, so these conditions are skipped to allow other conditions to be evaluated properly.
Ignore filter type of "flag" which nobody can create yet, but is coming soon.
> fix: Ignore new `flag` filter type in local evaluation

- posthog-react-native/CHANGELOG.md
- posthog-react-native/package.json
- posthog-react-native/src/hooks/useNavigationTracker.ts
helps with https://github.com/PostHog/posthog-js-lite/issues/560
> fix: read the navigation ref from the current property if it exists for expo-router and @react-navigation/native

- bin/fmt
- bin/helpers/_utils.sh
Adding a `fmt` script to this repo as described by https://posthog.com/handbook/engineering/conventions/scripts.
Because this repo builds so many projects, the other scripts will take more thought.
I always forget what command to run when I'm editing a bunch of SDKs.
Adds a bin script.
No version change needed. It's purely a developer experience thing.
> chore: Add bin/fmt script

- posthog-react-native/CHANGELOG.md
- posthog-react-native/babel.config.js
- posthog-react-native/package.json
As described in #495, react-native apps will currently show a warning when using posthog-react-native:
```
WARN  Your app (or one of its dependencies) is using an outdated JSX transform. Update to the modern JSX transform for faster performance: https://react.dev/link/new-jsx-transform
```
The documentation describes how to fix the issue:
```
Currently, the old transform {"runtime": "classic"} is the default option. To enable the new transform, you can pass {"runtime": "automatic"} as an option to @babel/plugin-transform-react-jsx or @babel/preset-react:
// If you are using @babel/preset-react
{
"presets": [
["@babel/preset-react", {
"runtime": "automatic"
}]
]
}
```
I have added the configuration above and verified that the `React.createElement`-statements are gone from the output.
- …
> Solve `outdated JSX transform` issue

- posthog-web/README.md
Fixes documentation missing a codeblock terminator
See before and after of that README
None, documentation-only change
None
> docs: fix overflowing code block

- .github/workflows/release.yml
not sure who created npm_token but its been there for 5y, assuming its the 'org' token
all repos now are part of the posthog developers team
developers team belong to posthog org
https://github.com/PostHog/posthog-js-lite/settings/secrets/actions
> fix: remove bens token
