- posthog-core/src/index.ts
- posthog-core/src/types.ts
- posthog-core/test/posthog.featureflags.spec.ts
- posthog-core/test/posthog.identify.spec.ts
- posthog-core/test/posthog.reset.spec.ts
- posthog-react-native/src/posthog-rn.ts
@neilkakkar quick eyes on this would be great just to roughly see that it looks sensible
> Fixed anonymous id calls

- posthog-core/src/index.ts
- posthog-core/src/types.ts
- posthog-core/test/posthog.featureflags.spec.ts
- posthog-node/src/posthog-node.ts
> fix: Remove decide endpoint timer

- posthog-react-native/package.json
Related Docs: https://github.com/PostHog/posthog.com/pull/3837
Related main repo: https://github.com/PostHog/posthog-react-native/pull/66
> release: React Native v2.0.0

- posthog-node/CHANGELOG.md
- posthog-node/package.json
Fixes https://github.com/PostHog/posthog-node/issues/75
Goes in after https://github.com/PostHog/posthog-js-lite/pull/16
> Bump PostHog-node version

- posthog-react-native/CHANGELOG.md
- posthog-react-native/package.json
https://posthogusers.slack.com/archives/C01GLBKHKQT/p1669028421333179
Install RN with async storage currently doesn't work
> Release new version with minor fixes

- posthog-node/CHANGELOG.md
- posthog-node/package.json
- posthog-node/src/posthog-node.ts
> fix: timeouts for local evaluation

- posthog-react-native/README.md
need to import posthog provider (in example) to use it.
Fixed in docs too: https://github.com/PostHog/posthog.com/pull/5036
> need to import posthog provider

- .github/workflows/release.yml
- posthog-web/package.json
This is an old PR and probably should have been merged a while back... Better late than never! 🙈
> Release js-lite to 2.0.0

- package.json
- posthog-core/package.json
- posthog-node/CHANGELOG.md
- posthog-node/package.json
- posthog-react-native/CHANGELOG.md
- posthog-react-native/package.json
- posthog-web/package.json
release updated version with json payload
- updates changelogs
- bumps a minor version
> chore: release new version with v3 decide

- posthog-core/src/index.ts
- posthog-node/src/posthog-node.ts
Suggested changes to simplify even further
> wip: Fix node to extend from stateless class

- posthog-core/src/index.ts
- posthog-node/CHANGELOG.md
- posthog-node/package.json
- posthog-node/test/posthog-node.spec.ts
Fixes https://github.com/PostHog/posthog/issues/13092
> fix: Ensure shutdown waits for pending promises

- examples/example-node/example.ts
- posthog-node/CHANGELOG.md
- posthog-node/package.json
- posthog-node/src/posthog-node.ts
- posthog-node/src/types.ts
- posthog-node/test/posthog-node.spec.ts
> fix: Allow sending distinctID and fix bug with active flags

- posthog-core/src/index.ts
- posthog-core/src/types.ts
- posthog-node/CHANGELOG.md
- posthog-node/package.json
- posthog-node/src/posthog-node.ts
- posthog-node/src/types.ts
- posthog-node/test/feature-flags.spec.ts
- posthog-node/test/posthog-node.spec.ts
Companion to https://github.com/PostHog/posthog-python/pull/98
> feat: Default to disabling geoIP resolution

- README.md
Noticed people having a hard time finding these
> chore: Add links to changelog

- posthog-node/CHANGELOG.md
- posthog-node/package.json
> release version 3.1.1 of node

- posthog-core/test/posthog.featureflags.spec.ts
- posthog-node/CHANGELOG.md
- posthog-node/package.json
- posthog-node/src/posthog-node.ts
- posthog-node/test/posthog-node.spec.ts
^^ These events can't be used properly in experiments right now, because they're missing flag info used for experiments
> fix(flags): Make sure to add feature props to ffc events

- posthog-react-native/package.json
Follow up https://github.com/PostHog/posthog-js-lite/pull/146
Forgot to change the version
> Update RN version to 2.9.2

- posthog-react-native/package.json
Forgot to bump the version so it's not released yet
> chore: bump rn version

- posthog-react-native/CHANGELOG.md
- posthog-react-native/package.json
> chore: add changelog for 2.10.2

- posthog-node/README.md
- posthog-react-native/README.md
> chore: community page

- posthog-react-native/CHANGELOG.md
- posthog-react-native/package.json
> chore: release rn 2.11.6

- posthog-core/src/index.ts
- posthog-core/test/posthog.featureflags.spec.ts
- posthog-node/CHANGELOG.md
- posthog-node/src/feature-flags.ts
- posthog-node/src/posthog-node.ts
- posthog-react-native/CHANGELOG.md
- posthog-react-native/src/posthog-rn.ts
Implements https://github.com/PostHog/posthog/issues/852 for node and RN
> chore: set user-agent for non browser apps

- posthog-core/src/index.ts
- posthog-core/src/types.ts
- posthog-core/test/posthog.enqueue.spec.ts
- posthog-node/CHANGELOG.md
- posthog-react-native/CHANGELOG.md
- posthog-web/CHANGELOG.md
One more improvement for https://github.com/PostHog/posthog-js-lite/issues/176
> chore: add maxQueueSize support

- posthog-react-native/CHANGELOG.md
- posthog-react-native/package.json
> chore: release rn 3.1.0

- posthog-core/src/types.ts
- posthog-react-native/src/posthog-rn.ts
> chore: remove old comment

- posthog-node/CHANGELOG.md
- posthog-node/package.json
- posthog-react-native/CHANGELOG.md
- posthog-react-native/package.json
Reason https://github.com/PostHog/posthog-js-lite/pull/247
> chore: new node patch release

- examples/example_rn/posthog.tsx
- yarn.lock
> fix: rn session replay example

- examples/example_rn/package.json
- posthog-react-native/CHANGELOG.md
- posthog-react-native/package.json
- yarn.lock
Closes https://github.com/PostHog/posthog/issues/13269
> chore: session replay for rn

- posthog-core/src/index.ts
- posthog-react-native/CHANGELOG.md
- posthog-react-native/package.json
- posthog-react-native/src/posthog-rn.ts
- posthog-react-native/tsconfig.json
- yarn.lock
Addresses part of https://github.com/PostHog/posthog-react-native-session-replay/issues/10
> fix: session replay respects the disabled flag

- posthog-react-native/src/types.ts
Relates to https://github.com/PostHog/posthog-android/pull/206
> fix: maskAllTextInputs desc

- posthog-node/README.md
- posthog-react-native/README.md
> fix: readme links

- posthog-node/src/types.ts
- addresses the feedback described in this ticket: https://posthoghelp.zendesk.com/agent/tickets/22430
- ships with the associated docs change for posthog.com: https://github.com/PostHog/posthog.com/pull/10334
> chore(docs): update docs around getFeatureFlagPayload based on some customer feedback

- posthog-web/README.md
This pull request addresses a typo in the `README.md` file. Specifically, the word "offically" has been corrected to "officially".
- Fixed typo in the README.md file from "offically" to "officially".
> chore: Typo fix  README.md

- posthog-ai/README.md
- posthog-ai/package.json
- posthog-node/CHANGELOG.md
- posthog-node/package.json
> fix: release package

- posthog-ai/package.json
move to deps for now while looking for fix
> chore: bump

- posthog-ai/README.md
- posthog-ai/package.json
- posthog-ai/src/openai/index.ts
- posthog-ai/src/utils.ts
- posthog-ai/src/vercel/middleware.ts
Map Vercel AI to out Posthog Event
> feat: map vercel to same format

- posthog-ai/package.json
- posthog-ai/src/index.ts
- posthog-ai/src/openai/azure.ts
- posthog-ai/src/openai/index.ts
- posthog-ai/src/utils.ts
- posthog-ai/src/vercel/middleware.ts
Added field $ai_is_error as a bool and stringified the error into $ai_error so we can show errors in the ui
Adde AzureOpenAI to the package
> feat: error handling and azure

- posthog-ai/package.json
- posthog-ai/src/anthropic/index.ts
- posthog-ai/src/index.ts
- posthog-ai/src/openai/azure.ts
- posthog-ai/src/openai/index.ts
- posthog-ai/src/utils.ts
Adding to match python sdk + feature requests from beta users
Added anthroipic wrapper for SDK
Posthog-ai
- Added support for Anthropic SDK
> feat: add anthropic support for sdk

- .github/pull_request_template.md
- .github/workflows/ci.yml
- CHANGELOG.md
- CONTRIBUTING.md
- package.json
- posthog-ai/CHANGELOG.md
> chore: ai repo has changelog, radme link, etc

- posthog-ai/src/langchain/callbacks.ts
> fix pr link

- examples/example-expo-latest/package.json
- examples/example_rn/package.json
- posthog-react-native/CHANGELOG.md
- posthog-react-native/package.json
- posthog-react-native/src/posthog-rn.ts
- posthog-react-native/src/types.ts
- yarn.lock
> chore: Session Replay - GA

- posthog-web/README.md
A comment in `posthog-web`'s Readme is incorrect, added a minor fix.
Changed the comment in Readme.
- Readme changes in `posthog-web`
> Update readme: fix comment

- posthog-ai/CHANGELOG.md
- posthog-ai/package.json
- posthog-ai/src/anthropic/index.ts
- posthog-ai/src/openai/azure.ts
- posthog-ai/src/openai/index.ts
Streaming not working as expected
Splti stream and return original stream object
> feat: change streaming support to split stream an return original

- posthog-ai/CHANGELOG.md
- posthog-ai/package.json
- posthog-ai/src/vercel/middleware.ts
> fix: support old version of ai sdk

- examples/example-expo-latest/App.tsx
- posthog-core/src/index.ts
- posthog-core/src/types.ts
- posthog-react-native/src/posthog-rn.ts
- posthog-react-native/src/surveys/PostHogSurveyProvider.tsx
> chore: remote config for surveys

- posthog-react-native/src/surveys/PostHogSurveyProvider.tsx
- posthog-react-native/src/surveys/Readme.md
- posthog-react-native/src/surveys/components/BottomSection.tsx
- posthog-react-native/src/surveys/components/QuestionTypes.tsx
- posthog-react-native/src/surveys/components/SurveyModal.tsx
- posthog-react-native/src/surveys/components/Surveys.tsx
- posthog-react-native/src/surveys/getActiveMatchingSurveys.ts
- posthog-react-native/src/surveys/surveys-utils.ts
> fix: next question and a few other things

- posthog-react-native/src/PostHogProvider.tsx
There's a typo
Fixed a typo
- [c] posthog-react-native
- Fixed the world's smallest typo in PostHogProvider
> fix: Error messaging in PostHogProvider

- posthog-core/src/surveys-types.ts
- posthog-react-native/src/native-deps.tsx
- posthog-react-native/src/surveys/PostHogSurveyProvider.tsx
- posthog-react-native/src/surveys/components/SurveyModal.tsx
- posthog-react-native/src/surveys/getActiveMatchingSurveys.ts
- posthog-react-native/src/surveys/index.ts
- posthog-react-native/src/surveys/surveys-utils.ts
> feat: device type check

- posthog-web/README.md
> fix: readme web typo

- examples/example-expo-latest/App.tsx
- examples/example-expo-latest/package.json
- posthog-core/src/index.ts
- posthog-react-native/package.json
- posthog-react-native/src/posthog-rn.ts
- posthog-react-native/src/surveys/PostHogSurveyProvider.tsx
- posthog-react-native/src/surveys/components/ConfirmationMessage.tsx
- posthog-react-native/src/surveys/components/QuestionHeader.tsx
- posthog-react-native/src/surveys/components/QuestionTypes.tsx
- yarn.lock
> fix: clean up and fix a few things

- posthog-ai/CHANGELOG.md
- posthog-ai/package.json
- posthog-ai/src/anthropic/index.ts
- posthog-ai/src/langchain/callbacks.ts
- posthog-ai/src/openai/azure.ts
- posthog-ai/src/openai/index.ts
- posthog-ai/src/utils.ts
- posthog-ai/src/vercel/middleware.ts
- posthog-ai/tests/openai.test.ts
- feat: add reasoning and cache tokens to openai and anthropic
- feat: add tool support for vercel
- feat: add support for other media types vercel
> feat: cached + reasoning tokens

- posthog-ai/CHANGELOG.md
- posthog-ai/package.json
- posthog-ai/src/langchain/callbacks.ts
langchain is not using runName so $ai_span_name is incorrectly set
Fix langchain name
> fix: langchain name + usage

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
> chore: add ai issue template item

- posthog-react-native/CHANGELOG.md
- posthog-react-native/package.json
- posthog-react-native/src/surveys/components/SurveyModal.tsx
Closes https://github.com/PostHog/posthog/issues/30858
> fix: Survey modal now moves up when the keyboard is open

- posthog-core/src/surveys-types.ts
- posthog-node/CHANGELOG.md
- posthog-node/package.json
Closes https://github.com/PostHog/posthog-js-lite/issues/448
Solution powered by ChatGPT :D
> export top-level declarations for surveys

- posthog-core/src/surveys-types.ts
- posthog-node/CHANGELOG.md
- posthog-node/package.json
Closes https://github.com/PostHog/posthog-js-lite/issues/448
Follow up #449
> export and declare top-level declarations for surveys

- posthog-react-native/CHANGELOG.md
- posthog-react-native/package.json
- posthog-react-native/src/surveys/getActiveMatchingSurveys.ts
Follow up https://github.com/PostHog/posthog-js-lite/pull/452/
> broken relative imports for surveys

- posthog-react-native/CHANGELOG.md
> chore: update rn changelog

- .github/workflows/bundle-size.yml
> chore: add ai package to bundle size workflow

- posthog-core/src/index.ts
- posthog-core/src/utils.ts
- posthog-node/CHANGELOG.md
- posthog-node/package.json
- posthog-react-native/src/posthog-rn.ts
> chore: better error logging when flushing events

- posthog-ai/CHANGELOG.md
- posthog-ai/package.json
- posthog-ai/tests/openai.test.ts
- posthog-core/package.json
- posthog-node/CHANGELOG.md
- posthog-node/package.json
bump to rebuild all new versions together and deploy to npm
> chore: bump versions

- posthog-core/src/index.ts
- posthog-react-native/CHANGELOG.md
- posthog-react-native/package.json
- posthog-react-native/src/surveys/components/SurveyModal.tsx
Closes https://github.com/PostHog/posthog-js-lite/issues/472
> fix: survey modal closes when clicking inside the modal

- posthog-core/src/index.ts
- posthog-core/src/utils.ts
- posthog-react-native/CHANGELOG.md
Closes https://github.com/PostHog/posthog-js-lite/issues/500
> fix: use custom allSettled implementation to avoid issues with patching Promise

- posthog-core/src/featureFlagUtils.ts
- posthog-core/src/index.ts
- posthog-react-native/CHANGELOG.md
- posthog-react-native/package.json
- posthog-react-native/src/posthog-rn.ts
https://posthog.slack.com/archives/C04MZFDA5KK/p1746644228860679
bug introduced by the [migration of the flags endpoint](https://github.com/PostHog/posthog-js-lite/pull/458/)
> fix: session recording respects linked flags

- posthog-core/src/index.ts
[](https://posthog.slack.com/archives/C03P7NL6RMW/p1747902905788819?thread_ts=1747885516.960799&cid=C03P7NL6RMW)
> chore: flush method comments

- posthog-node/CHANGELOG.md
- posthog-node/package.json
> chore: release node 4.17.2

- .github/workflows/ci.yml
- .github/workflows/release.yml
- posthog-ai/CHANGELOG.md
- posthog-ai/package.json
- posthog-ai/src/gemini/index.ts
- posthog-ai/src/index.ts
- posthog-ai/src/utils.ts
- posthog-ai/tests/gemini.test.ts
- yarn.lock
Adding support for @google/genai to LLM observability
> feat: gemini support

- examples/example-expo-latest/App.tsx
- examples/example_expo_rn_web/App.tsx
- examples/example_rn/posthog.tsx
- posthog-core/src/index.ts
- posthog-core/src/types.ts
- posthog-core/test/posthog.setProperties.spec.ts
- posthog-node/CHANGELOG.md
- posthog-react-native/CHANGELOG.md
- posthog-react-native/src/PostHogProvider.tsx
- posthog-react-native/src/posthog-rn.ts
- posthog-react-native/src/types.ts
- posthog-react-native/test/posthog.spec.ts
- posthog-web/CHANGELOG.md
Closes https://github.com/PostHog/posthog-js-lite/issues/212
> chore: remove deprecated methods and options and rename stale props

- .github/workflows/call-flags-project-board.yml
This adds a workflow for the Feature Flags team's project board. See https://github.com/PostHog/.github/pull/1 for more context.
No changes to code.
> chore(flags): Add flags workflow

- posthog-nextjs/README.md
- posthog-nextjs/package.json
- create nextjs release
- fix vercel deployment
- fix posthog-cli resolution
> chore(nextjs): bump patch version

- posthog-nextjs-config/CHANGELOG.md
- posthog-nextjs-config/package.json
- Fix build issues on vercel deployment using latest cli version
- Fix build issues on vercel deployment (xz system library missing)
> fix(err): fix vercel build process

- examples/example-expo-53/app/_layout.tsx
> fix: rn expo router sample

- posthog-ai/CHANGELOG.md
- posthog-ai/package.json
- posthog-ai/src/anthropic/index.ts
- posthog-ai/src/gemini/index.ts
- posthog-ai/src/openai/azure.ts
- posthog-ai/src/openai/index.ts
- posthog-ai/src/vercel/middleware.ts
- posthog-ai/tests/gemini.test.ts
- posthog-ai/tests/openai.test.ts
Anonymous events were not working due to distinct id override to early in the flow
fix this
> fix: anonymous events were not working due to distinct id override
